# Generated by Django 5.1.4 on 2025-02-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0003_alter_post_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
