# Generated by Django 5.1.8 on 2025-04-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_course_image_alter_rating_rating"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="CourseContents",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="CourseContents",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="CourseContents",
            name="content_type",
            field=models.CharField(
                choices=[("video", "Video"), ("pdf", "PDF"), ("article", "Article")],
                max_length=20,
            ),
        ),
    ]
