# Generated by Django 5.1.8 on 2025-04-15 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_image_alter_rating_rating'),
        ('courses', '0002_initial'),
    ]

    operations = [
    ]
