# Generated by Django 5.1.4 on 2025-01-19 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_enrollment_student_rating_user"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("course", "user")},
        ),
        migrations.AlterField(
            model_name="course",
            name="ratings",
            field=models.FloatField(default=0.0),
        ),
        migrations.RemoveField(
            model_name="coursecontents",
            name="course",
        ),
        migrations.AlterField(
            model_name="rating",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings_set",
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("course", "student")},
        ),
        migrations.RemoveField(
            model_name="rating",
            name="feedback",
        ),
        migrations.AddField(
            model_name="coursecontents",
            name="course",
            field=models.ManyToManyField(related_name="contents", to="courses.course"),
        ),
    ]
