# Generated by Django 5.1.4 on 2025-02-22 06:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_alter_coursecontents_text_content_alter_rating_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coursecontents",
            old_name="file_link",
            new_name="url",
        ),
        migrations.RemoveField(
            model_name="coursecontents",
            name="video_url",
        ),
    ]
